server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:33061/mjudb
    username: root
    password: pwd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.example: DEBUG