name: CD - Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/back-end
            sudo docker compose -f compose-prod.yml down --volumes --remove-orphans
            git pull origin main
            ./gradlew clean build -x test
            sudo docker compose -f compose-prod.yml up --build -d
